apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: guestbook-monitor
  namespace: monitoring
  labels:
    app: guestbook
    release: prometheus
spec:
  selector:
    matchLabels:
      app: guestbook
  endpoints:
  - port: http
    interval: 30s
    path: /info
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-metrics-blue
  namespace: default
  labels:
    app: guestbook
    version: blue
spec:
  selector:
    app: guestbook
    version: blue
  ports:
  - name: http
    port: 3030
    targetPort: 3030
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-metrics-green
  namespace: default
  labels:
    app: guestbook
    version: green
spec:
  selector:
    app: guestbook
    version: green
  ports:
  - name: http
    port: 3030
    targetPort: 3030
    protocol: TCP
  type: ClusterIP