apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-simple
  labels:
    app: redis-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-simple
  template:
    metadata:
      labels:
        app: redis-simple
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-simple-service
  labels:
    app: redis-simple
spec:
  selector:
    app: redis-simple
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP